# This is a basic workflow to help you get started with Actions

name: Build and Test Automata4j

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build-automata4j:
      # runner images with architectures (variants)
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ 'ubuntu-latest' ]
      name: Build Automata4j

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: Checkout Job
          uses: actions/checkout@v3

        - name: Setup Temurin-JDK-19
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin' 
            java-version: '19'

        - name: Compiling java
          run: ./gradlew --console="verbose" :automata4j:build

        - name: Archive build
          uses: actions/upload-artifact@v3
          with:
            name: snaploader-snapshot
            path: automata4j/build/libs/

    test-doc-generation:
        # a linux runner image with the ndk installed and llvm ready to compile android native binaries
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ 'ubuntu-latest' ]
        name: Generating documentation

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          - name: Checkout Job
            uses: actions/checkout@v3
          
          - name: Setup Oracle-JDK-19
            uses: actions/setup-java@v3
            with:
              distribution: 'temurin' 
              java-version: '19'

          - name: Generate javadoc
            run: chmod +rwx ./gradlew && ./gradlew :automata4j:generateJavadocJar

    test:
        # runner images with architectures (variants)
        runs-on: ${{ matrix.os }}
        needs: build-automata4j
        strategy:
          matrix:
            os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        name: Testing automata4j on ${{ matrix.os }} for x86-64

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          - name: Checkout Job
            uses: actions/checkout@v3
          
          - name: Setup Temurin-JDK-19
            uses: actions/setup-java@v3
            with:
              distribution: 'temurin' 
              java-version: '19'
          
          - name: Download automata4j-SNAPSHOT.jar library
            uses: actions/download-artifact@v3
            with:
              name: automata4j-snapshot
              path: automata4j/build/libs/

          - name: Run SerialAdder example
            run: ./gradlew :automata4j-examples:run
